/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yhkfwzhcnhkeroiaembu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inloa2Z3emhjbmhrZXJvaWFlbWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4Njg0NjQsImV4cCI6MjA4MDQ0NDQ2NH0.8yyQ-gY64IJyKkpcoPDSZok-4T2vYIX-hRluC7Jy3Ks"